spring:
  aop:
    proxy-target-class: true

  datasource:
    continue-on-error: true
    initialize: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
      hibernate.id.new_generator_mappings: true
      hibernate.jdbc.fetch_size: 100
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.cache.use_second_level_cache: false

  batch:
    initializer:
      enabled: false

  mvc:
    favicon:
      enabled: false

jsf:
  state-saving-method: server
  datetimeconverter-default-timezone-is-system-timezone: true

  primefaces:
    theme: omega
    uploader: commons
    client-side-validation: true
    public-captcha-key: 6LfwZwoAAAAAAI-oUHpdvRnkMfu9fXQHxc0P7IBu
    private-captcha-key: 6LfwZwoAAAAAAEhRyntKF1PBzysAJLzqp2v-GMRR

# Development environment
---
spring:
  profiles: development

# DataSource
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@docker:1521/xe.oracle.docker
    username: oagi
    password: oagi
    platform: oracle

logging:
  level:
    org.oagi.srt: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

jsf:
  project-stage: Development

server:
  session:
    timeout: 6000000
    cookie:
      max-age: 6000000

# Staging environment
---
spring:
  profiles: staging

# DataSource
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/OAGISRTDB
    username: oagi
    password: oagi
    platform: oracle

jsf:
  project-stage: Production

server:
  session:
    timeout: 6000000
    cookie:
      max-age: 6000000

# Production environment
---
spring:
  profiles: production
  main:
    banner-mode: off

# DataSource
  datasource:
    jndi-name: ${datasource.jndi-name}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    platform: oracle

jsf:
  project-stage: Production